---
- name: start docker-compose-drone-server
  become: true
  docker_service:
    project_src: "{{ drone_server_workspace_dir }}"
    state: present

- name: restart docker-compose-drone-server
  become: true
  docker_service:
    project_src: "{{ drone_server_workspace_dir }}"
    state: present
    restarted: yes

- name: stop docker-compose-drone-server
  become: true
  docker_service:
    project_src: "{{ drone_server_workspace_dir }}"
    state: absent
